### PR TITLE
Relay config by json

### PR DESCRIPTION
**Pull request by mattn**
Possible to use custom relay servers.

### CODE REVIEW

**Comment by fiatjaf** [comment]
can you move the list of trusted pubkeys to a single environment variable, just so we don't have pubkeys in the relays config?

like
```
TRUSTED_PUBKEYS=7bdef7be22dd8e59f4600e044aa53a1cf975a9dc7d27df5833bc77db784a5805,3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d,97c70a44366a6535c145b333f973ea86dfdc2d7a99da618c40c64705ad98e322,ee11a5dff40c19a555f41fe42b48f00e618c91225622ae37b6c2bb67b76c4e49
```

I think this will work if you just declare the variable on envconfig  as `[]string`.

**Comment by mattn** [comment]
Only trusted pubkeys or other fields too?

**Comment by fiatjaf** [comment]
Just the trusted pubkeys, since they are not relays it's confusing to have them in the relay config file.

**Comment by mattn** [comment]
Updated. How can I test last change?

**Comment by fiatjaf** [comment]
What do you mean? You need an environment variable like

```
TRUSTED_PUBKEYS=7bdef7be22dd8e59f4600e044aa53a1cf975a9dc7d27df5833bc77db784a5805,3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d,97c70a44366a6535c145b333f973ea86dfdc2d7a99da618c40c64705ad98e322,ee11a5dff40c19a555f41fe42b48f00e618c91225622ae37b6c2bb67b76c4e49
```

**Comment by fiatjaf** [comment]
Thank for this change, by the way.

**Comment by mattn** [comment]
> What do you mean? You need an environment variable like

I dont understand how trusted pubkeys behaves.

**Comment by fiatjaf** [comment]
They are just used for prefetching a bunch of profiles and serving them as the result of the "try a random link" thing on the homepage.

**Pull request merged**
