### PR TITLE
Add profile json

### PR DESCRIPTION
**Pull request by mattn**
This can be used by webapp to get profile.

### CODE REVIEW

**Comment by dtonon** [comment]
Njump should not be an http API, otherwise it discourages appropriate use via websockets.
@fiatjaf ?

**Comment by mattn** [comment]
However, the browser has no way of knowing from which relay provided that event, so the same event may not be available in websocket.

**Comment by fiatjaf** [comment]
Yes, webapps should not rely on njump. This breaks Nostr.

**Comment by mattn** [comment]
Okay, closing.

**Pull request closed without merging**
