### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by 0xtrr**
I saw #3 and figured it wouldn't be hard to add a simple Dockerfile to this project. Is this something you want in this repo?

### CODE REVIEW

**Comment by fiatjaf** [comment]
Honestly, I personally hate Docker and don't want it, but I guess we should accept this PR because you had all this trouble.

**Comment by 0xtrr** [comment]
Don't worry about me, no need to merge this if you don't want it in the codebase.

**Comment by fiatjaf** [comment]
@0xtrr can you update the Dockerfile to include a command to build the Tailwind CSS bundle?

This is the command:

```
tailwind -i tailwind.css -o static/tailwind-bundle.min.css --minify
```

But you also have to install the [Tailwind CLI](https://tailwindcss.com/docs/installation).

**Comment by 0xtrr** [comment]
> @0xtrr can you update the Dockerfile to include a command to build the Tailwind CSS bundle?
> 
> This is the command:
> 
> ```
> tailwind -i tailwind.css -o static/tailwind-bundle.min.css --minify
> ```
> 
> But you also have to install the [Tailwind CLI](https://tailwindcss.com/docs/installation).

https://github.com/fiatjaf/njump/pull/9

**Pull request merged**
